version: "3.1"
services:
  db:
    image: mariadb
    container_name: coworkingspace_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: supersafePwd123
    volumes:
      - ./database:/var/lib/mysql